spring:
  profiles:
    active: local

product:
  img:
    path: classpath:static/img/product

---

spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

spring:
  profiles: prd

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true # SQL을 보기 좋게 바꿔줌
        use_sql_comments: true # 어떤 Entity를 사용하는지 코멘트로 출력

  datasource:
    url: jdbc:mysql://10.138.0.2:3306/uglyAgriFood?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: homework
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE